/**
 * M1.6 — 前端 Edition Gate 类型系统。
 *
 * FeatureCode 枚举常量（保持与后端 editions/features.py 同步）。
 * 如果后端新增了 code，前端这里不用立刻追加上，hasFeature('XXX') 仍可按字符串工作；
 * 但推荐新增时同步写入便于类型检查。
 */

export type EditionName = 'community' | 'enterprise';
export type TierName = 'community' | 'starter' | 'professional' | 'enterprise' | 'ultimate';

/** 常用 Feature Code 快捷常量（只列常用的，更多用字符串传递即可） */
export const FEATURES = {
	// 系统
	COLUMN_PERMISSION: 'COLUMN_PERMISSION',
	DATA_PERMISSION_MATRIX: 'DATA_PERMISSION_MATRIX',
	WHITELIST_ADVANCED: 'WHITELIST_ADVANCED',
	BACKUP_RESTORE: 'BACKUP_RESTORE',
	DOWNLOAD_CENTER: 'DOWNLOAD_CENTER',
	SSO_LDAP: 'SSO_LDAP',
	// 主机
	HOST_MONITOR_METRICS: 'HOST_MONITOR_METRICS',
	HEARTBEAT_SERVER_CLUSTER: 'HEARTBEAT_SERVER_CLUSTER',
	CA_CRL_MANAGEMENT: 'CA_CRL_MANAGEMENT',
	// 运维执行
	OPS_PILOT_CANARY: 'OPS_PILOT_CANARY',
	OPS_EXECUTION_APPROVAL: 'OPS_EXECUTION_APPROVAL',
	OPS_EXECUTION_NOTIFICATION: 'OPS_EXECUTION_NOTIFICATION',
	// 脚本库
	SCRIPT_VERSION_FULL: 'SCRIPT_VERSION_FULL',
	SCRIPT_PERMISSION_FINEGRAINED: 'SCRIPT_PERMISSION_FINEGRAINED',
	SCRIPT_OFFICIAL_MARKET_FULL: 'SCRIPT_OFFICIAL_MARKET_FULL',
	SCRIPT_OFFICIAL_MARKET_CE: 'SCRIPT_OFFICIAL_MARKET_CE',
	SCRIPT_SECURITY_CHECK: 'SCRIPT_SECURITY_CHECK',
	SCRIPT_APPROVAL_FLOW: 'SCRIPT_APPROVAL_FLOW',
	SCRIPT_AUDIT_LOG: 'SCRIPT_AUDIT_LOG',
	SCRIPT_SHARING: 'SCRIPT_SHARING',
	// 工作流
	WORKFLOW_DAG_ENGINE: 'WORKFLOW_DAG_ENGINE',
	WORKFLOW_DAG_VERSIONING: 'WORKFLOW_DAG_VERSIONING',
	WORKFLOW_APPROVAL_FLOW: 'WORKFLOW_APPROVAL_FLOW',
	WORKFLOW_SHARING: 'WORKFLOW_SHARING',
	WORKFLOW_RISK_ASSESSMENT: 'WORKFLOW_RISK_ASSESSMENT',
	// 调度
	SCHEDULE_STANDALONE_CE: 'SCHEDULE_STANDALONE_CE',
	SCHEDULE_HA_CLUSTER: 'SCHEDULE_HA_CLUSTER',
	SCRIPT_TASK_UNIFIED: 'SCRIPT_TASK_UNIFIED',
	SCHEDULE_ALERT_RETRY: 'SCHEDULE_ALERT_RETRY',
	// 程序管理
	PROGRAM_COMMAND_BATCH: 'PROGRAM_COMMAND_BATCH',
	PROGRAM_INSTALL_TEMPLATE: 'PROGRAM_INSTALL_TEMPLATE',
	PROGRAM_INSTALL_POLICY: 'PROGRAM_INSTALL_POLICY',
	PROGRAM_HOST_BINDING: 'PROGRAM_HOST_BINDING',
	PROGRAM_INSTALL_CONFIG: 'PROGRAM_INSTALL_CONFIG',
	// 日志 + 扩展中心
	HOST_LOG_FORWARDING: 'HOST_LOG_FORWARDING',
	LOG_COMMAND_CONTROL: 'LOG_COMMAND_CONTROL',
	KNOWLEDGE_BASE: 'KNOWLEDGE_BASE',
	INSPECTION_CENTER: 'INSPECTION_CENTER',
	TOOLS_CENTER: 'TOOLS_CENTER',
	TICKET_CENTER: 'TICKET_CENTER',
	TASK_CENTER: 'TASK_CENTER',
	SHARE_ACTIVATE_PAGE: 'SHARE_ACTIVATE_PAGE',
	CONTACT_LEAD_PORTAL: 'CONTACT_LEAD_PORTAL',
} as const;

export type FeatureCode = string;
