import { registerNodeManifest } from '../manifest/registry.ts'

registerNodeManifest({
  nodeType: 'wait',
  displayName: '等待',
  category: 'control',
  color: '#409EFF',
  icon: '⏱',
  description: '等待后继续执行，支持固定延时和每天定时两种模式',
  requiresHost: false,
  isAsynchronousHuman: false,
  inputs: ['in'],
  outputs: ['out'],
  params: [
    {
      key: 'wait_mode',
      label: '等待模式',
      type: 'select',
      required: true,
      group: '基础配置',
      options: [
        { label: '固定延时（再等多久）', value: 'delay' },
        { label: '每天定时（每天几点）', value: 'daily_time' },
      ],
      defaultValue: 'delay',
    },
    {
      key: 'delay_seconds',
      label: '延时秒数',
      type: 'number',
      group: '基础配置',
      required: true,
      defaultValue: 60,
      min: 1,
      max: 31536000,
      visibleWhen: { wait_mode: 'delay' },
      help: '相对时长等待，如 30 表示等待 30 秒',
    },
    {
      key: 'daily_time',
      label: '每天定时',
      type: 'time-picker',
      group: '基础配置',
      required: true,
      defaultValue: '02:00:00',
      visibleWhen: { wait_mode: 'daily_time' },
      help: '每天固定时刻（HH:mm:ss），到达该节点后等待下一个该时刻',
    },
    {
      key: 'expired_strategy',
      label: '过期策略',
      type: 'select',
      group: '基础配置',
      required: true,
      visibleWhen: { wait_mode: 'daily_time' },
      options: [
        { label: '立即执行', value: 'execute_now' },
        { label: '跳过本节点', value: 'skip' },
        { label: '流程失败', value: 'fail' },
      ],
      defaultValue: 'execute_now',
      help: '到达节点时目标时间已过的处理方式',
    },
  ],
  outputSchema: [
    { key: 'wake_at', label: '唤醒时间', type: 'text' },
    { key: 'woke_at', label: '实际唤醒时间', type: 'text' },
    { key: 'overtime_seconds', label: '超时秒数', type: 'number' },
    { key: 'daily_time', label: '定时时刻', type: 'text' },
    { key: 'expired', label: '是否过期', type: 'boolean' },
    { key: 'expired_strategy', label: '过期策略', type: 'text' },
    { key: 'skipped', label: '是否跳过', type: 'boolean' },
  ],
})
